image: yglukhov/nim-base

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "running test"

build:
  stage: build
  script: echo "build stage"

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  only:
    - maser
